### ISSUE TITLE
no support for custom user models...

### ISSUE THREAD

**Issue by puterleat** [avallbona/Impostor#10]
See 

impostor.ImpostorLog.imposted_as: (fields.E301) Field defines a relation with the model 'auth.User', which has been swapped out.
    HINT: Update the relation to point at 'settings.AUTH_USER_MODEL'.
impostor.ImpostorLog.impostor: (fields.E301) Field defines a relation with the model 'auth.User', which has been swapped out.
    HINT: Update the relation to point at 'settings.AUTH_USER_MODEL'.

**Comment by avallbona** [comment]
Hi @puterleat, with the new version this feature is supported.Kind regards
