### ISSUE TITLE
The link to the pypi page is broken

### ISSUE THREAD

**Issue by IgnacioMaestro** [avallbona/Impostor#48]
In the readme file, the python package link is pointing to https://github.com/avallbona/Impostor/workflows/Python%20package/badge.svg?branch=master instead of [https://pypi.org/project/Impostor/.](https://github.com/avallbona/Impostor/workflows/python%20package/badge.svg?branch=master)

**Comment by avallbona** [comment]
thanks, merged your pr. 🌹
